---
- hosts: all
  gather_facts: true
  become: true
  become_user: lorenzo
  tasks:
    - name: localbin
      file:
        path: /home/lorenzo/.local/bin
        state: directory
    - name: Download starship
      get_url:
        url: https://github.com/starship/starship/releases/download/v1.14.2/starship-x86_64-unknown-linux-gnu.tar.gz
        dest: /tmp/starship.tar.gz
    - name: Download atuin
      get_url:
        url: https://github.com/ellie/atuin/releases/download/v14.0.1/atuin-v14.0.1-x86_64-unknown-linux-gnu.tar.gz
        dest: /tmp/atuin.tar.gz
    - name: Unarchive
      unarchive:
        src: "/tmp/{{ item }}"
        dest: /home/lorenzo/.local/bin
        remote_src: true
      loop:
        - starship.tar.gz
        - atuin.tar.gz

