---
- hosts: all
  gather_facts: true
  become: true
  become_user: lorenzo
  vars:
    myuser: lorenzo
    bindir: ".local/bin"
  tasks:
    - name: localbin
      file:
        path: /home/{{ myuser }}/{{ bindir }}
        state: directory
    - name: in the path
      lineinfile:
        dest: /home/{{ myuser }}/.bashrc
        line: "export PATH=/home/{{ myuser }}/{{ bindir }}:$PATH"
    - name: Download starship
      get_url:
        url: https://github.com/starship/starship/releases/download/v1.14.2/starship-x86_64-unknown-linux-gnu.tar.gz
        dest: /tmp/starship.tar.gz
    - name: Download atuin
      get_url:
        url: https://github.com/ellie/atuin/releases/download/v14.0.1/atuin-v14.0.1-x86_64-unknown-linux-gnu.tar.gz
        dest: /tmp/atuin.tar.gz
    - name: Unarchive
      unarchive:
        src: "/tmp/{{ item }}"
        dest: /home/{{ myuser }}/{{ bindir }}
        remote_src: true
      loop:
        - starship.tar.gz
        - atuin.tar.gz
    - name: config
      file:
        path: /home/{{ myuser }}/.config
        state: directory
    - name: Configure starship
      shell: |
        /home/{{ myuser }}/{{ bindir }}/starship preset tokyo-night -o ~/.config/starship.toml
    - name: Set in bashrc
      lineinfile:
        path: /home/{{ myuser }}/.bashrc
        state: present
        line: 'eval "$(starship init bash)"'


