---
- hosts: all
  gather_facts: false
  become: true
  tasks:
    - name: AllowAgentForwarding (set YES to NO)
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^[#]{0,1}AllowAgentForwarding'
        line: AllowAgentForwarding no
    - name: AllowAgentForwarding (set YES to NO)
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^[#]{0,1}AllowTcpForwarding'
        line: AllowTcpForwarding no
    - name: ClientAliveCountMax (set 3 to 2)
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^[#]{0,1}ClientAliveCountMax'
        line: ClientAliveCountMax 2
    - name: LogLevel (set INFO to VERBOSE)
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^[#]{0,1}LogLevel'
        line: LogLevel VERBOSE
    - name: MaxAuthTries (set 6 to 3)
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^[#]{0,1}MaxAuthTries'
        line: MaxAuthTries 3
    - name: MaxSessions (set 10 to 2)
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^[#]{0,1}MaxSessions'
        line: MaxSessions 2
    - name: TCPKeepAlive (set YES to NO)
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^[#]{0,1}TCPKeepAlive'
        line: TCPKeepAlive no
    - name: X11Forwarding (set YES to NO)
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^[#]{0,1}X11Forwarding'
        line: X11Forwarding no
    - name: No Root Login
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^[#]{0.1}PermitRootLogin'
        line: PermitRootLogin no
    - name: No PasswordAuthentication
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^[#]{0.1}PermitRootLogin'
        line: PermitRootLogin no
    - name: No PermitEmptyPasswords
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^[#]{0.1}PermitEmptyPasswords'
        line: PermitEmptyPasswords no
    - name: Restart ssh
      service:
        name: ssh
        state: restarted
    - name: disable protocols dcp, dccp_diag, rds, sctp, tipc
      copy:
        dest: /etc/modprobe.d/CIS.conf
        content: |
          install dccp /bin/true
          install dccp_diag /bin/true
          install rds /bin/true
          install sctp /bin/true
          install tipc /bin/true
          install usb-storage /bin/true
    - name: install packages
      apt:
        name:
          - apt-show-versions
          - debsums
        state: present
    - name: banner
      copy:
        dest: "{{ item }}"
        content: |
          #################################################################
          #                   _    _           _   _                      #
          #                  / \  | | ___ _ __| |_| |                     #
          #                 / _ \ | |/ _ \ '__| __| |                     #
          #                / ___ \| |  __/ |  | |_|_|                     #
          #               /_/   \_\_|\___|_|   \__(_)                     #
          #                                                               #
          #  You are entering into a secured area! Your IP, Login Time,   #
          #   Username has been noted and has been sent to the server     #
          #                       administrator!                          #
          #   This service is restricted to authorized users only. All    #
          #            activities on this system are logged.              #
          #  Unauthorized access will be fully investigated and reported  #
          #        to the appropriate law enforcement agencies.           #
          #################################################################
        loop:
          - /etc/issue
          - /etc/issue.net

          
