---
- hosts: all
  gather_facts: false
  become: true
  tasks:
    - name: AllowAgentForwarding (set YES to NO)
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^[#]{0,1}AllowAgentForwarding'
        line: AllowAgentForwarding no
