- name: Update apt cache
  apt:
    update_cache: true
    force_apt_get: true
    cache_valid_time: 3600
  become: true

- name: Upgrade packages
  apt:
    upgrade: dist
  become: true

- name: Check if reboot required
  stat:
    path: /var/run/reboot-required
  register: reboot_required_file
  become: true

- name: Reboot if required
  reboot:
  when: reboot_required_file.stat.exists == true
  become: true
