---
- name: Importar clave GPG del repositorio de Podman
  apt_key:
    url: https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_22.04/Release.key
    state: present
  tags: podman

- name: Agregar repositorio de Podman
  apt_repository:
    repo: deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_22.04 ./ # podman
    state: present
    update_cache: yes
    filename: podman
  tags: podman

- name: Actualizar lista de paquetes
  apt:
    update_cache: yes

- name: Instalar dependencias de Podman
  apt:
    name:
    - slirp4netns
    - podman
    state: present

# systemctl --user enable --now podman.socket
- name: Start podman socket
  systemd:
    name: podman.socket
    state: enable
    scope: user
  register: result
  become: yes
  become_user: lorenzo
- debug:
    var: result.stdout


- name: Instalar podman-compose vía pip
  pip:
    name: podman-compose
